### ISSUE TITLE
Invalid characters in query can result in a fail to save the properties

### ISSUE THREAD

**Issue by orpiske** [orpiske/maestro-java#24]
For example, using $

```
ERROR 10:29:59,611  net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager - Unable to start workers from the container: Illegal character in query at index 120: tcp://host:61616/test.performance.queue?protocol=OPENWIRE&durable=false&appendClientNumber=${APPEND_CLIENT_NUMBER}
java.net.URISyntaxException: Illegal character in query at index 120: tcp://host:61616/test.performance.queue?protocol=OPENWIRE&durable=false&appendClientNumber=${APPEND_CLIENT_NUMBER}
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3111)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at net.orpiske.mpt.common.URLQuery.<init>(URLQuery.java:27)
        at net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager.writeTestProperties(MaestroWorkerManager.java:152)
        at net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager.doWorkerStart(MaestroWorkerManager.java:174)
        at net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager.handle(MaestroWorkerManager.java:315)
        at net.orpiske.mpt.maestro.notes.StartSender.notify(StartSender.java:26)
        at net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager.noteArrived(MaestroWorkerManager.java:72)
        at net.orpiske.mpt.maestro.worker.base.MaestroWorkerManager.noteArrived(MaestroWorkerManager.java:25)
        at net.orpiske.mpt.maestro.client.AbstractMaestroPeer.messageArrived(AbstractMaestroPeer.java:131)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
        at at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by orpiske** [comment]
Another problem: when this happen, no success/failure notification is sent.
